In [48]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression

In [81]:
dataset = pd.read_excel('train.xlsx')

In [82]:
# pd.unique(dataset['Degree'])
# pd.unique(dataset['Specialization'])

In [83]:
encoder = LabelEncoder()
deg = encoder.fit_transform(dataset['Degree'])

In [84]:
dataset['Degree'] = deg

In [95]:
X = dataset.iloc[:,[9,12,15,16,18,23]].values
y = dataset['Salary'].values

In [96]:
deg = deg.reshape(-1,1)
onehot = OneHotEncoder(categories='auto')
X = onehot.fit_transform(X)

In [97]:
y = y.reshape(-1,1)
std = StandardScaler()
# X = std.fit_transform(X)
y = std.fit_transform(y)

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [98]:
X.toarray()[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [99]:
reg = LinearRegression()
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [100]:
pred = reg.predict(X)

In [101]:
pred[0]

array([0.45134109])

In [102]:
mean_squared_error(y,pred)

0.3467485930387938

In [103]:
pred = std.inverse_transform(pred)

In [104]:
pred[0]

array([403705.01511689])