In [7]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "height" : [6.0,6.4,5.8,5.9,5.7,5.11,5.9,5.10,6.2,5.8,5.4,5.6,5.2,5.0,5.1,5.4,5.3,4.9,4.8,5.1],
    "weight" : [80,89,70,72,66,73,69,73,81,70,56,58,51,49,60,52,48,49,53,58],
    "gender" : ['m','m','m','m','m','m','m','m','m','m','f','f','f','f','f','f','f','f','f','f',]
}

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
encoder = LabelEncoder()
data['gender'] = encoder.fit_transform(data['gender'])

In [5]:
data['gender']

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [8]:
df = pd.DataFrame(data)

X = df[['height','weight']].values
y = df['gender']

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [14]:
def svm(x,y,epochs,alpha):
    w = np.zeros(2)
    for epoch in range(1,epochs):
        for i in range(len(x)):
            if y[i] * x[i].dot(w) < 1:
                w = w + alpha * ((y[i] * x[i]) - (2 * (1/epoch) * w))
            else:
                w = w + alpha * (-2 * (1/epoch) * w )
    return w

In [27]:
epochs = 10000
alpha = 0.1
weights = svm(X,y,epochs,alpha)

In [28]:
weights

array([1.12574616, 2.56654449])

In [29]:
pred = X.dot(weights)

In [30]:
pred

array([ 4.8090392 ,  7.77494821,  2.1306186 ,  2.81775648,  1.00876577,
        1.04097275,  2.16568406,  1.01573046,  5.53124255,  2.1306186 ,
       -1.92207778, -0.98251696, -3.51371102, -4.45327184, -1.80991669,
       -2.79150767, -3.9133605 , -4.70569477, -4.08868782, -2.24463164])