In [1]:
import numpy as np

In [2]:
x = np.array([3,4,5,7,6,4,4,6,67])

In [3]:
x1 = [5,6,6,4,3,56,6,7,4,4]

In [4]:
x

array([ 3,  4,  5,  7,  6,  4,  4,  6, 67])

In [5]:
x1

[5, 6, 6, 4, 3, 56, 6, 7, 4, 4]

In [6]:
type(x)

numpy.ndarray

In [7]:
type(x1)

list

In [8]:
x1 = np.array([4,5,56,7,9,5,4,4,6,3.4,34.77])

In [9]:
x1

array([ 4.  ,  5.  , 56.  ,  7.  ,  9.  ,  5.  ,  4.  ,  4.  ,  6.  ,
        3.4 , 34.77])

In [10]:
x2 = np.array([4,5,6,6,3,3,"hello"])

In [11]:
x2

array(['4', '5', '6', '6', '3', '3', 'hello'], dtype='<U11')

In [12]:
x3 = np.array([3,5,6,6,4,3,6,7,10.5,True])

In [13]:
x3

array([ 3. ,  5. ,  6. ,  6. ,  4. ,  3. ,  6. ,  7. , 10.5,  1. ])

In [14]:
x3[4]

4.0

In [15]:
x3[:4]

array([3., 5., 6., 6.])

In [16]:
import sys

In [17]:
sys.getsizeof(list())

64

In [19]:
sys.getsizeof(np.array([]))

96

In [30]:
list_1 = list(range(1,100000))
arr_1 = np.array(list_1)

In [31]:
# list_1

In [32]:
# arr_1

In [33]:
sys.getsizeof(list_1)

900096

In [34]:
sys.getsizeof(arr_1)

400092