In [1]:
import numpy as np

# Ways to create array in numpy

In [2]:
# First Method
x = np.array([4,5,7,3,4,7,8,1])

In [3]:
print(x)

[4 5 7 3 4 7 8 1]


In [10]:
# second method
x2 = np.arange(100,500,15)

In [11]:
print(x2)

[100 115 130 145 160 175 190 205 220 235 250 265 280 295 310 325 340 355
 370 385 400 415 430 445 460 475 490]


In [12]:
# third method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# forth method
np.linspace(1,10,num=12)

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [19]:
np.linspace(1,10,num=12,retstep=True)

(array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
         5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
         9.18181818, 10.        ]), 0.8181818181818182)

In [26]:
# fifth method
np.ndarray((2,2,2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 5.73116149e-321],
        [1.33511290e-306, 1.78012156e-306]]])

In [27]:
#sixth method
np.random

<module 'numpy.random' from 'C:\\Users\\asus\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [29]:
# will return a random number b/w 0 and 1
np.random.random()

0.4609113938577025

In [34]:
np.random.random() * 50

39.696386281652366

In [35]:
np.random.random(size=(4,4))

array([[0.23416838, 0.80332185, 0.89993754, 0.70587559],
       [0.04609003, 0.49653811, 0.67967803, 0.70891579],
       [0.30400202, 0.09096484, 0.97506131, 0.12751752],
       [0.94829646, 0.1741778 , 0.26929648, 0.4466033 ]])

In [36]:
np.random.random(size=(4,4)) * 5

array([[1.58761205, 3.78175958, 2.64741688, 4.35575802],
       [3.07473726, 0.43340821, 3.08254304, 3.06248223],
       [0.75492002, 0.66680185, 1.22094309, 2.34751704],
       [0.67935479, 3.38906312, 2.40037823, 4.18575718]])

In [49]:
np.random.seed(8)
np.random.randint(10)

3

In [38]:
np.random.randint(10,100)

34

In [40]:
np.random.randint(10,100,18)

array([60, 93, 14, 97, 35, 64, 94, 86, 67, 16, 98, 71, 14, 13, 85, 91, 44,
       32])

# Slicing of array

In [50]:
x = np.array([[4,5,3,5,8,8],[8,6,4,6,8,4],[3,4,9,5,4,3],[4,7,8,5,4,3]])

In [51]:
x

array([[4, 5, 3, 5, 8, 8],
       [8, 6, 4, 6, 8, 4],
       [3, 4, 9, 5, 4, 3],
       [4, 7, 8, 5, 4, 3]])

In [52]:
x.shape

(4, 6)

In [53]:
x.ndim

2

In [54]:
x[:2]

array([[4, 5, 3, 5, 8, 8],
       [8, 6, 4, 6, 8, 4]])

In [56]:
x[:,:2]

array([[4, 5],
       [8, 6],
       [3, 4],
       [4, 7]])

In [57]:
x[:,2:4]

array([[3, 5],
       [4, 6],
       [9, 5],
       [8, 5]])

In [58]:
x[2:4,2:4]

array([[9, 5],
       [8, 5]])