In [1]:
import numpy as np

In [14]:
x = np.random.randint(10,1000,40)

In [3]:
x

array([312, 165, 431, 273, 105, 613, 598, 237, 265,  64, 829, 723, 460,
       958,  13, 729, 237, 956,  68, 655, 603, 886, 791, 739, 414, 881,
       785,  98, 142, 486, 718, 660,  54, 568,  88, 855, 612, 736, 840,
       815])

In [4]:
x.mean()

511.55

In [5]:
x.max()

958

In [6]:
x.min()

13

In [7]:
x.argmax()

13

In [8]:
x[13]

958

In [9]:
x.argmin()

14

In [10]:
x.argsort()

array([14, 32,  9, 18, 34, 27,  4, 28,  1, 16,  7,  8,  3,  0, 24,  2, 12,
       29, 33,  6, 20, 36,  5, 19, 31, 30, 11, 15, 37, 23, 26, 22, 39, 10,
       38, 35, 25, 21, 17, 13], dtype=int64)

In [15]:
x.sort()

In [16]:
x

array([ 21,  76, 104, 112, 205, 238, 239, 249, 262, 272, 298, 305, 325,
       349, 399, 402, 454, 498, 559, 593, 632, 672, 685, 689, 699, 738,
       744, 790, 797, 846, 881, 912, 921, 926, 950, 956, 958, 963, 996,
       999])

In [17]:
x[::-1]

array([999, 996, 963, 958, 956, 950, 926, 921, 912, 881, 846, 797, 790,
       744, 738, 699, 689, 685, 672, 632, 593, 559, 498, 454, 402, 399,
       349, 325, 305, 298, 272, 262, 249, 239, 238, 205, 112, 104,  76,
        21])

In [18]:
x.shape

(40,)

In [19]:
x.reshape(4,10)

array([[ 21,  76, 104, 112, 205, 238, 239, 249, 262, 272],
       [298, 305, 325, 349, 399, 402, 454, 498, 559, 593],
       [632, 672, 685, 689, 699, 738, 744, 790, 797, 846],
       [881, 912, 921, 926, 950, 956, 958, 963, 996, 999]])

In [20]:
x.reshape(5,8)

array([[ 21,  76, 104, 112, 205, 238, 239, 249],
       [262, 272, 298, 305, 325, 349, 399, 402],
       [454, 498, 559, 593, 632, 672, 685, 689],
       [699, 738, 744, 790, 797, 846, 881, 912],
       [921, 926, 950, 956, 958, 963, 996, 999]])

In [23]:
x = x.reshape(-1,8)

In [24]:
x

array([[ 21,  76, 104, 112, 205, 238, 239, 249],
       [262, 272, 298, 305, 325, 349, 399, 402],
       [454, 498, 559, 593, 632, 672, 685, 689],
       [699, 738, 744, 790, 797, 846, 881, 912],
       [921, 926, 950, 956, 958, 963, 996, 999]])

In [25]:
x.flatten()

array([ 21,  76, 104, 112, 205, 238, 239, 249, 262, 272, 298, 305, 325,
       349, 399, 402, 454, 498, 559, 593, 632, 672, 685, 689, 699, 738,
       744, 790, 797, 846, 881, 912, 921, 926, 950, 956, 958, 963, 996,
       999])

In [28]:
x = np.array([[4,5,5,6,67,23,5],[5,6,7,4,4,5,7]])

In [29]:
np.hstack(x)

array([ 4,  5,  5,  6, 67, 23,  5,  5,  6,  7,  4,  4,  5,  7])

In [30]:
np.vstack(x)

array([[ 4,  5,  5,  6, 67, 23,  5],
       [ 5,  6,  7,  4,  4,  5,  7]])